parameters:
  test_runner_settings:
    max_idle_time: 3900
    max_execution_time: 30
    keep_alive_interval_time: 60 #0 for none
    keep_alive_tolerance_time: 130
    r_environ_path: /usr/src/concerto/R/.Renviron
    php_exec: /usr/local/bin/php
    rscript_exec: /usr/bin/Rscript
    timer_type: server #client or server
    session_forking: false #only linux, only on PersistantSessionRunnerService, experimental
    dir: /
    connection: local
    dmtcp_bin_path: /usr/src/dmtcp/bin
    checkpointed_session_init: true #only linux, only on CheckpointSessionRunnerService, experimental

services:
  Concerto\TestBundle\Service\ASessionRunnerService: '@Concerto\TestBundle\Service\PersistantSessionRunnerService'
  #Concerto\TestBundle\Service\ASessionRunnerService: '@Concerto\TestBundle\Service\CheckpointSessionRunnerService' #only linux, experimental